# Generated by Django 2.2 on 2019-04-22 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_status', models.CharField(choices=[('re', 'reserved'), ('ca', 'cancle')], default='re', max_length=2)),
                ('reserve_token', models.CharField(max_length=64)),
                ('reserve_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('re', 'register_user'), ('gu', 'guess_user')], default='gu', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Register_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=255)),
                ('user_lname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.User')),
            ],
        ),
        migrations.CreateModel(
            name='Parking_slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('parking_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.Parking_zone')),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrive_at', models.DateField()),
                ('leave_at', models.DateField()),
                ('parking_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.Parking_slot')),
                ('parking_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.Parking_zone')),
                ('reservation', models.ManyToManyField(to='customer.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_license_number', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('car_brand', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_color', models.CharField(max_length=50)),
                ('register_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.Register_user')),
            ],
        ),
    ]
