# Generated by Django 2.2 on 2019-04-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_user',
            name='point',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
    ]
