# Generated by Django 2.2 on 2019-04-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_register_user_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_user',
            name='email',
            field=models.EmailField(default='pp@pp.com', max_length=254),
            preserve_default=False,
        ),
    ]
