# Generated by Django 2.2 on 2019-04-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20190428_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='arrive_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='leave_at',
            field=models.DateField(null=True),
        ),
    ]
