# Generated by Django 2.2 on 2019-05-03 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20190430_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regist_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('user_fname', models.CharField(max_length=255)),
                ('user_lname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('point', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.User_sys')),
            ],
        ),
    ]
