# Generated by Django 2.2 on 2019-05-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_regist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='reservation',
        ),
        migrations.AddField(
            model_name='parking_slot',
            name='reservation',
            field=models.ManyToManyField(to='customer.Reservation'),
        ),
    ]
