# Generated by Django 2.2 on 2019-05-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20190503_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('re', 'register_user'), ('gu', 'guess_user')], default='gu', max_length=2)),
            ],
        ),
    ]
