# Generated by Django 2.2 on 2019-05-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='parking_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
