# Generated by Django 2.2 on 2019-05-04 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_parking_parking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='register_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='customer.Register_user'),
            preserve_default=False,
        ),
    ]
