# Generated by Django 2.2 on 2019-05-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20190509_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='point_use',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
